### ISSUE TITLE
GO slimmer

### ISSUE THREAD

**Issue by keuv-grvl** [PPiMapBuilder/PPiMapBuilder#15]
Slim the Gene Ontology for visual layout. A dedicated GO slim must be done (https://www.ebi.ac.uk/QuickGO/GMultiTerm)

**Comment by gcornut** [comment]
You are right, we can use QuickGO as a GO slimmer Webservice.
example:

```
http://www.ebi.ac.uk/QuickGO/GAnnotation?protein=P12345,P20384&format=tsv&termUse=slim&goid=GO:0016740,GO:0000150
```

Will display GO terms for the protein P12345 and P0404 (`protein` parameter) slimmed using only GO:0016740 and GO:0000150 (`goid` parameter) as possible displayed terms. 

It seems very powerful. We could make big request for a whole network. Some other parameters would even make the request fully optimized (`gz` => gunzip compression of the text result and `col` => to reduce number of data columns)
