### ISSUE TITLE
Customizable organism list

### ISSUE THREAD

**Issue by gcornut** [PPiMapBuilder/PPiMapBuilder#21]
The user should be able to add or remove organisms in the list given by PMB.
I thought it would be better to have the user search for his organism using the E-Utilities web service from the NCBI through a search field in the PMB settings window. That way we prevent error and we are sure of the data in the organism list.
http://www.ncbi.nlm.nih.gov/books/NBK25499/#chapter4.ESearch

The `esearch.fcgi` interface will bring result to the user searches.
The `efetch.fcgi` interface would then be able to recover all data about the species selected by the user (if the result of esearch is not enough).

**Comment by pidupuis** [comment]
This issue is now finished. Finally we stored the entire inparanoid organism list and use it as a repository for user search.
