### ISSUE TITLE
Update company name

### ISSUE THREAD

**Issue by keuv-grvl** [PPiMapBuilder/PPiMapBuilder#26]
Change the current _bundle.symbolicName_, _bundle.namespace_ and _groupId_ in **_pom.xml_** to something more revelant.
Current : tk.nomis_tech
Suggestion: **ch.picard** (or _ch.unige_)

**Comment by gcornut** [comment]
We talked about it with Pierre. It will be done after merging code from
Pierre and me, just before the publishing of v0.9 to make sure no conflict
occurs.
But thanks for writting this issue, it will be a memo for us just before
submission of v0.9.

2014-05-12 15:51 GMT+02:00 keuv-gravouil notifications@github.com:

**Comment by pidupuis** [comment]
Also change the package name from <i>tk.nomis_tech</i> to </i>ch.picard</i>.
