### ISSUE TITLE
Choose a software licence

### ISSUE THREAD

**Issue by pidupuis** [PPiMapBuilder/PPiMapBuilder#29]
We need to choose an open source licence.
The following site can help us: http://choosealicense.com/

**Comment by pidupuis** [comment]
Cytoscape is released using the GPL licence, see [here](http://cytoscape.org/download.php) which means we have to use it too I think.

**Comment by pabloech** [comment]
yes, we have to use that one

On Thu, Apr 23, 2015 at 6:16 PM, Pierre Dupuis notifications@github.com
wrote:

> Cytoscape is released using the GPL licence, see here
> http://cytoscape.org/download.php which means we have to use it too I
> think.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PPiMapBuilder/PPiMapBuilder/issues/29#issuecomment-95637505
> .

## 

Pablo Echeverria, PhD
Pablo.Echeverria@unige.ch
+41 22 3796811
Departement de Biologie Cellulaire
Universite de Geneve
Sciences III
30, Quai Ernest Ansermet
CH - 1211 Geneve 4
Switzerland

**Comment by pidupuis** [comment]
Done in v0.11
