### ISSUE TITLE
New UniProtKB accession number format in release 2014_06

### ISSUE THREAD

**Issue by keuv-grvl** [PPiMapBuilder/PPiMapBuilder#33]
The Uniprot accession number format will change soon. Some changes might be required. See: http://www.uniprot.org/changes/accession_format

**Comment by pidupuis** [comment]
Thanks for this issue. We'll try to handle it for the 0.10 version.

**Comment by gcornut** [comment]
Actually it's simple. It's just a RegExp expression to change. I'll do it for v0.9 since I refactored a little the UniProt utils.
