### ISSUE TITLE
Scrollable credit frame?

### ISSUE THREAD

**Issue by keuv-grvl** [PPiMapBuilder/PPiMapBuilder#34]
With my look and feel (Ocean? Metal?) cut the bottom of the credit frame.
![image](https://cloud.githubusercontent.com/assets/2539879/3042812/c72cd39e-e100-11e3-9084-d29c9b7e79bd.png)

**Comment by pidupuis** [comment]
Yes, this is due to linux look and feel. We already opened an issue for this and more generally to improve the entire credit frame.

See https://github.com/PPiMapBuilder/PPiMapBuilder/issues/28.
