### ISSUE TITLE
Update organism autocompletion after changes in prefered organism list

### ISSUE THREAD

**Issue by keuv-grvl** [PPiMapBuilder/PPiMapBuilder#35]
When I delete an organism from _Settings > Organisms_, this organism will not appear in the search box if I don't click on _Save_ then reopen this windows. It could be a good idea to refresh the "not prefered organism" list after deleting an element in the "prefered organism" list.

**Comment by pidupuis** [comment]
We do not have this problem (in Ubuntu and MacOS). The searchbox is automatically rebuild after deletion without needed to save and reopen...
