### ISSUE TITLE
Do not close Settings window when "Save" is clicked

### ISSUE THREAD

**Issue by keuv-grvl** [PPiMapBuilder/PPiMapBuilder#36]
And replace "Cancel" button by a "Close" button.
When I change something in the settings, I would like to click on _Save_, see the changes, and close this window when I decide.

**Comment by pidupuis** [comment]
Fair enough but I think the cancel option can be useful anyway. Maybe a reset button can be added too.

I think we need to discuss about it all together soon, because we are currently working on the setting window so I think this is the moment to add these corrections.
