### ISSUE TITLE
Nodes without gene name

### ISSUE THREAD

**Issue by pidupuis** [PPiMapBuilder/PPiMapBuilder#46]
A network can display nodes without gene name, reported [here](https://github.com/PPiMapBuilder/PPiMapBuilder/issues/45#issuecomment-95648779). These nodes are consequently blanks.

For example:
- POI:
  - P31948
- Organisms:
  - H. sapiens
  - S. cerevisiae
  - S. pombe
  - M. musculus
  - R. norvegicus
  - P. falciparum
- Databases:
  - BioGrid
  - DIP
  - IntAct
  - MINT

We obtain several nodes without gene name:
- [Q308M6](http://www.uniprot.org/uniprot/Q308M6)
- [Q59GL9](http://www.uniprot.org/uniprot/Q59GL9)
- [Q59GT1](http://www.uniprot.org/uniprot/Q59GT1)
- [Q86SX1](http://www.uniprot.org/uniprot/Q86SX1)
- [Q8TA90](http://www.uniprot.org/uniprot/Q8TA90)
- [Q9BZG7](http://www.uniprot.org/uniprot/Q9BZG7)

As we can see in Uniprot for each of these proteins, there is no assigned gene name and that's specifically from Uniprot that our app fetches the protein information.

So that's not a bug, but we need to find a solution to fill the blank. Any idea ?

**Comment by keuv-grvl** [comment]
I may suggest (in my personal order of preference):
- the protein name (with a flag showing it's not a gene name, such as "[ptn]DNA polymerase")
- the Uniprot ID (not informative)
- "<N/A>" (as Uniprot do, but not informative either).

**Comment by pidupuis** [comment]
I agree that the first option could be the best. But in practice, the protein name is often a really long sentence. 

For now I'm using N/A (in v0.11), waiting for a better solution...
