### ISSUE TITLE
background vs node color

### ISSUE THREAD

**Issue by pabloech** [PPiMapBuilder/PPiMapBuilder#54]
after PMB layout or on big networks, the visualisation of the whole network it's difficult, there's no contratst all looks so white. I think that the background should keep white but the nodes should be in RGB (0, 102, 204) a light blue. the node line border could rise till 2 pt (stroke).

**Comment by pidupuis** [comment]
No problem but we'll need to choose a new node label color (which is a lighter blue for now)

**Comment by pidupuis** [comment]
Done in v0.12
