### ISSUE TITLE
Should the interactome query contain interactions predicted by homology ? 

### ISSUE THREAD

**Issue by pidupuis** [PPiMapBuilder/PPiMapBuilder#62]
A POI network can contain interactions predicted by homology.

For now, an entire interactome generated for a specific specie is restricted to this specie and does not include predictions from other organisms sharing their proteins. But basically, the same prediction system can be applied in interactome.

**Comment by pabloech** [comment]
No I think it's too much. Just to retrieve the entire interactome from one organism is enough.
But from a POI it's ok if we can now their interolgs
